In [5]:
#check numpy version
import numpy as np
#np.__version__

In [9]:
lst = [1,2,"3",4,5]
arr1 = np.array(lst)
##arr1 = np.array((1,2,"3",4,5))
arr1
#print(type(arr1))

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [10]:
#when you have to create an array in rnage
arr2 = np.arange(1,10)
arr2


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [13]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr5 = np.linspace(1,10,5)
arr5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
## 1D array to 2D array
arr6 = np.arange(1,31).reshape(5,6)
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [24]:
#arr7 = np.random.randint(1,100,10)
arr7 = np.random.random(10)
arr7

array([0.42823933, 0.05505583, 0.48474048, 0.45468151, 0.71490081,
       0.79275101, 0.44783078, 0.18524759, 0.51044676, 0.05188277])

In [40]:
arr8 = np.arange(60).reshape(12,5)
print(arr8.shape)
print(arr8.dtype)
print(arr8.size)
print(arr8.ndim)


(12, 5)
int64
60
2


In [36]:
##multidimension array to 1D
arr8.ravel()
arr8.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr8 = np.arange(60).reshape(12,5)
print(arr8.shape)
arr9 = arr8.T.shape
arr9

(12, 5)


(5, 12)

In [38]:
#indexing and slicing
#2D array  -- [row start]

In [ ]:
arr8[9:10,4:5][0][0]


np.int64(49)

In [66]:
#arr8[::-1,:]
arr8[::-1,::-1]


array([[ 59,  58,  57,  56,  55],
       [ 54,  53,  52,  51,  50],
       [ 49,  48,  47,  46,  45],
       [ 44,  43,  42,  41,  40],
       [ 39,  38,  37,  36,  35],
       [ 34,  33,  32,  31,  30],
       [ 29,  28, 100,  26,  25],
       [ 24,  23, 100,  21,  20],
       [ 19,  18,  49,  16,  15],
       [ 14,  13,  12,  11,  10],
       [  9,   8,   7,   6,   5],
       [  4,   3,   2,   1,   0]])

In [6]:
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
arr11 = np.arange(25).reshape(5,5)
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
arr10[2:4]

array([[[150, 151, 152, 153, 154],
        [155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164],
        [165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174],
        [175, 176, 177, 178, 179],
        [180, 181, 182, 183, 184],
        [185, 186, 187, 188, 189],
        [190, 191, 192, 193, 194],
        [195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204],
        [205, 206, 207, 208, 209],
        [210, 211, 212, 213, 214],
        [215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224]]])